# Generated by Django 5.0.6 on 2024-06-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="privacy",
            field=models.CharField(default="public", max_length=10),
            preserve_default=False,
        ),
    ]
